In [1]:
import sys
import os

root_path = os.path.abspath(os.path.join('..'))

if root_path not in sys.path:
    sys.path.append(root_path)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
raw = pd.read_csv('..\\data\\raw\\games.csv', index_col= False)
raw.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...

In [4]:
raw.shape

(122611, 39)

In [5]:
raw.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DiscountDLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='str')

In [8]:
raw.iloc[0]

AppID                                                                   2539430
Name                                                 Black Dragon Mage Playtest
Release date                                                        Aug 1, 2023
Estimated owners                                                          0 - 0
Peak CCU                                                                      0
Required age                                                                  0
Price                                                                       0.0
DiscountDLC count                                                             0
About the game                                                                0
Supported languages                                                         NaN
Full audio languages                                                         []
Reviews                                                                      []
Header image                                                                NaN
Website                       https://shared.akamai.steamstatic.com/store_it...
Support url                                                                 NaN
Support email                                                               NaN
Windows                                                                     NaN
Mac                                                                        True
Linux                                                                     False
Metacritic score                                                          False
Metacritic url                                                                0
User score                                                                  NaN
Positive                                                                      0
Negative                                                                      0
Score rank                                                                    0
Achievements                                                                NaN
Recommendations                                                               0
Notes                                                                         0
Average playtime forever                                                    NaN
Average playtime two weeks                                                    0
Median playtime forever                                                       0
Median playtime two weeks                                                     0
Developers                                                                    0
Publishers                                                                  NaN
Categories                                                                  NaN
Genres                                                                      NaN
Tags                                                                        NaN
Screenshots                                                                 NaN
Movies                        https://shared.akamai.steamstatic.com/store_it...
Name: 0, dtype: object

In [7]:
raw.iloc[0].to_dict()

{'AppID': 2539430,
 'Name': 'Black Dragon Mage Playtest',
 'Release date': 'Aug 1, 2023',
 'Estimated owners': '0 - 0',
 'Peak CCU': 0,
 'Required age': 0,
 'Price': 0.0,
 'DiscountDLC count': 0,
 'About the game': 0,
 'Supported languages': nan,
 'Full audio languages': '[]',
 'Reviews': '[]',
 'Header image': nan,
 'Website': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/header.jpg?t=1699268702',
 'Support url': nan,
 'Support email': nan,
 'Windows': nan,
 'Mac': True,
 'Linux': False,
 'Metacritic score': False,
 'Metacritic url': 0,
 'User score': nan,
 'Positive': 0,
 'Negative': 0,
 'Score rank': 0,
 'Achievements': nan,
 'Recommendations': 0,
 'Notes': 0,
 'Average playtime forever': nan,
 'Average playtime two weeks': 0,
 'Median playtime forever': 0,
 'Median playtime two weeks': 0,
 'Developers': 0,
 'Publishers': nan,
 'Categories': nan,
 'Genres': nan,
 'Tags': nan,
 'Screenshots': nan,
 'Movies': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/ss_7d9504b958d0b143d053d31cb74b375daba338d6.1920x1080.jpg?t=1699268702,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/ss_85d2749d23e115b4d44e8ed1024c55a6be524fde.1920x1080.jpg?t=1699268702'}

In [10]:
print(raw.columns.shape)
print(len(raw.columns))

(39,)
39

In [11]:
raw.loc[1].to_dict()

{'AppID': 496350,
 'Name': 'Supipara - Chapter 1 Spring Has Come!',
 'Release date': 'Jul 29, 2016',
 'Estimated owners': '0 - 20000',
 'Peak CCU': 0,
 'Required age': 0,
 'Price': 5.24,
 'DiscountDLC count': 65,
 'About the game': 0,
 'Supported languages': "Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'",
 'Full audio languages': "['English']",
 'Reviews': '[]',
 'Header image': nan,
 'Website': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097',
 'Support url': 'http://mangagamer.org/supipara',
 'Support email': 'http://mangagamer.com',
 'Windows': 'support@mangagamer.com',
 'Mac': True,
 'Linux': False,
 'Metacritic score': False,
 'Metacritic url': 0,
 'User score': nan,
 'Positive': 0,
 'Negative': 252,
 'Score rank': 3,
 'Achievements': nan,
 'Recommendations': 0,
 'Notes': 231,
 'Average playtime forever': nan,
 'Average playtime two weeks': 8,
 'Median playtime forever': 0,
 'Median playtime two weeks': 8,
 'Developers': 0,
 'Publishers': 'minori',
 'Categories': 'MangaGamer',
 'Genres': 'Single-player,Steam Trading Cards,Steam Cloud,Family Sharing',
 'Tags': 'Adventure',
 'Screenshots': 'Adventure,Visual Novel,Anime,Cute',
 'Movies': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_0a5ff85870a1c2221e495b75a5c7b9e248eb3249.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_f53e18a6c7be8eeb39e7c8efff8395b444786f68.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_1f86a8d171a549c504acd6592f559fc4bd9bd448.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_f40b6e8e535047b60412b8f102b907cb2317d53d.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_32c2149186b260804a2a8bed8e595f36228f8e16.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_abc2fe50c29b2621ae970f846a1e11d2e66c7394.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_020efba82647ba7aeb72185ab0becfc53c68238f.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_3fa4c80d58d7c156d30a0098ed57a236257afc9c.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_96b7faa121b03555c6a31877fbcdac961bccdadc.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_d0bfd6e4501bf94d7cd7727d2f1d085a86d68adb.1920x1080.jpg?t=1725519097'}

In [12]:
raw.columns.tolist()

['AppID',
 'Name',
 'Release date',
 'Estimated owners',
 'Peak CCU',
 'Required age',
 'Price',
 'DiscountDLC count',
 'About the game',
 'Supported languages',
 'Full audio languages',
 'Reviews',
 'Header image',
 'Website',
 'Support url',
 'Support email',
 'Windows',
 'Mac',
 'Linux',
 'Metacritic score',
 'Metacritic url',
 'User score',
 'Positive',
 'Negative',
 'Score rank',
 'Achievements',
 'Recommendations',
 'Notes',
 'Average playtime forever',
 'Average playtime two weeks',
 'Median playtime forever',
 'Median playtime two weeks',
 'Developers',
 'Publishers',
 'Categories',
 'Genres',
 'Tags',
 'Screenshots',
 'Movies']

In [13]:
with open('../data/raw/games.csv', 'r', encoding='utf-8', errors='ignore') as f:
    for _ in range(3):
        print(f.readline())

AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies

2539430,"Black Dragon Mage Playtest","Aug 1, 2023","0 - 0",0,0,0.0,0,0,"","[]","[]","","https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/header.jpg?t=1699268702","","","",True,False,False,0,"",0,0,0,"",0,0,"",0,0,0,0,"","","","","","https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/ss_7d9504b958d0b143d053d31cb74b375daba338d6.1920x1080.jpg?t=1699268702,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/ss_85d2749d23e115b4d44e8ed1024c55a6be524fde.1920x1080.jpg?t=1699268702",""

496350,"Supipara - Chapter 1 Spring Has Come!","Jul 29, 2016","0 - 20000",0,0,5.24,65,0,"Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'","['English']","[]","","https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097","http://mangagamer.org/supipara","http://mangagamer.com","support@mangagamer.com",True,False,False,0,"",0,252,3,"",0,231,"",8,0,8,0,"minori","MangaGamer","Single-player,Steam Trading Cards,Steam Cloud,Family Sharing","Adventure","Adventure,Visual Novel,Anime,Cute","https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_0a5ff85870a1c2221e495b75a5c7b9e248eb3249.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_f53e18a6c7be8eeb39e7c8efff8395b444786f68.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_1f86a8d171a549c504acd6592f559fc4bd9bd448.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_f40b6e8e535047b60412b8f102b907cb2317d53d.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_32c2149186b260804a2a8bed8e595f36228f8e16.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_abc2fe50c29b2621ae970f846a1e11d2e66c7394.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_020efba82647ba7aeb72185ab0becfc53c68238f.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_3fa4c80d58d7c156d30a0098ed57a236257afc9c.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_96b7faa121b03555c6a31877fbcdac961bccdadc.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_d0bfd6e4501bf94d7cd7727d2f1d085a86d68adb.1920x1080.jpg?t=1725519097",""

In [14]:
raw[['About the game',
     'Supported languages',
     'Full audio languages']].head(10)

,About the game,Supported languages,Full audio languages
0,0,NaN,[]
1,0,"Springtime, April: when the cherry trees come ...",['English']
2,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']"
3,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean']
4,0,Its not just a Maze; its a Quest! Enter the ca...,['English']
5,0,A JOURNEY THROUGH HELL! Explore the most terri...,"['English', 'French', 'Italian', 'German', 'Sp..."
6,1,Building on the success of its acclaimed prede...,['English']
7,0,"Years ago, Ricardo Luger was in the wrong plac...",['English']
8,0,Hepta Beats is a 2D side-view platformer game ...,"['English', 'French', 'Italian', 'German', 'Sp..."
9,1,WARRNING Don't show Your mom this game. You kn...,"['English', 'French', 'Italian', 'German', 'Sp..."

In [15]:
raw['About the game'].value_counts(dropna=False).head(20)

About the game
0     104840
1      11299
2       2831
3       1154
4        601
5        388
6        241
7        179
8        162
10       109
9        109
11        63
12        53
13        45
15        34
16        33
14        33
17        30
18        24
22        23
Name: count, dtype: int64

In [16]:
raw[['About the game',
     'Supported languages',
     'Full audio languages',
     'Reviews']].head(5)

,About the game,Supported languages,Full audio languages,Reviews
0,0,NaN,[],[]
1,0,"Springtime, April: when the cherry trees come ...",['English'],[]
2,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[]
3,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean']
4,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English']

In [ ]:
#csv shows mistakes, changing it to the original json

In [ ]:
raw_json = pd.read_json('..\\data\\raw\\games.json').T

,index,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0,0.0,0,,,,,...,0,0,0 - 0,0,0,0,0,0,0,[]
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0,5.24,0,"Springtime, April: when the cherry trees come ...","Springtime, April: when the cherry trees come ...","Spring has come, and our protagonist, Yukinari...",,...,252,3,0 - 20000,8,0,8,0,65,0,"{'Adventure': 27, 'Visual Novel': 19, 'Anime':..."
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0,4.99,0,"Immerse yourself in the most beloved, mystical...","Immerse yourself in the most beloved, mystical...",Discover an entrancing and spectacular world!,,...,21,3,0 - 20000,0,0,0,0,0,0,"{'Casual': 83, 'Card Game': 52, 'Solitaire': 4..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",Yuha! I'll start the broadcast! Hakko's extrem...,,...,0,0,0 - 20000,0,0,0,0,0,1,[]
4,3631080,Maze Quest VR,"Apr 24, 2025",0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,,...,0,0,0 - 20000,0,0,0,0,0,0,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122606,4152910,完美传奇,"Jan 4, 2026",0,0.0,0,《完美传奇》游戏介绍 🔥【完美传奇——专属大陆的奇幻史诗！】🔥 🌍耗时两年匠心打造，诚意之作...,《完美传奇》游戏介绍 🔥【完美传奇——专属大陆的奇幻史诗！】🔥 🌍耗时两年匠心打造，诚意之作...,欢迎来到《完美传奇》！ 🌍专属大陆×自由探索，六道轮回剧情×百变BUFF搭配，一刀爆神装、机...,,...,0,0,0 - 0,0,0,0,0,0,0,[]
122607,4042800,Poker Fate - ACG Texas Hold'em,"Jan 3, 2026",0,0.0,0,Poker Fate – Choose your poker partner and ent...,Poker Fate – Choose your poker partner and ent...,Poker Fate is an anime-style Texas Hold'em gam...,,...,0,0,0 - 0,0,0,0,0,0,0,[]
122608,3522550,Adira Nusantara,"Jan 3, 2026",0,7.99,0,(Gif character) Adira Nusantara is a side-scro...,(Gif character) Adira Nusantara is a side-scro...,"Master authentic Silat combat as Adira, a fier...",,...,0,0,0 - 0,0,0,0,0,0,0,[]
122609,3680350,A Lenda de Niterói,"Jan 4, 2026",0,2.09,0,"Step into the role of Arariboia, a legendary I...","Step into the role of Arariboia, a legendary I...",Embark on Arariboia’s journey during the 16th-...,,...,0,0,0 - 0,0,0,0,0,0,0,[]
122610,4141790,[BEAT:KEEPER],"Jan 5, 2026",0,0.0,0,Exhibited at Vantan Game Academy – TOKYO GAME ...,Exhibited at Vantan Game Academy – TOKYO GAME ...,Vantan Game Academy TOKYO GAME SHOW 2025 Exhib...,,...,0,0,0 - 0,0,0,0,0,0,0,[]

In [22]:
raw_json = raw_json.reset_index()
raw = raw_json.rename(columns= {"index": "appID"})
raw.columns

Index(['level_0', 'appID', 'name', 'release_date', 'required_age', 'price',
       'dlc_count', 'detailed_description', 'about_the_game',
       'short_description', 'reviews', 'header_image', 'website',
       'support_url', 'support_email', 'windows', 'mac', 'linux',
       'metacritic_score', 'metacritic_url', 'achievements', 'recommendations',
       'notes', 'supported_languages', 'full_audio_languages', 'packages',
       'developers', 'publishers', 'categories', 'genres', 'screenshots',
       'movies', 'user_score', 'score_rank', 'positive', 'negative',
       'estimated_owners', 'average_playtime_forever',
       'average_playtime_2weeks', 'median_playtime_forever',
       'median_playtime_2weeks', 'discount', 'peak_ccu', 'tags'],
      dtype='str')

In [24]:
raw = raw[[
    'appID',
    'name',
    'release_date',
    'required_age',
    'price',
    'dlc_count',
    'reviews',
    'metacritic_score',
    'achievements',
    'recommendations',
    'supported_languages',
    'full_audio_languages',
    'developers',
    'publishers',
    'categories',
    'genres',
    'user_score',
    'score_rank',
    'positive',
    'negative',
    'estimated_owners',
    'average_playtime_forever',
    'average_playtime_2weeks',
    'peak_ccu',
    'tags'
]]

raw.to_csv('..\\data\\processed\\data.csv',index=False)